sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t chandanabalu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chandanabalu/docker-react npm run test